# Generated by Django 3.2.20 on 2023-08-27 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='dog_breed',
        ),
        migrations.AddField(
            model_name='post',
            name='pet',
            field=models.CharField(choices=[('dog', 'dog'), ('cat', 'cat'), ('rabbit', 'rabbit'), ('hamster', 'hamster'), ('bird', 'bird'), ('ferret', 'ferret'), ('reptile', 'reptile'), ('fish', 'fish'), ('horse', 'horse'), ('spider', 'spider'), ('frog', 'frog'), ('gerbil', 'gerbil'), ('chicken', 'chicken'), ('duck', 'duck'), ('cow', 'cow'), ('pig', 'pig'), ('guinea_pig', 'guinea pig')], default='none', max_length=30),
        ),
    ]
