# Generated by Django 3.2.20 on 2023-08-21 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_link',
            field=models.URLField(verbose_name='Event URL'),
        ),
    ]
