# Generated by Django 3.2.20 on 2023-08-22 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventcomments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventcomment',
            old_name='event',
            new_name='eventpost',
        ),
    ]
